---
title: Nutrients for nonhuman primate
author: Geebbon
date: '2018-03-12'
slug: nutrients-for-nonhuman-primate
categories:
  - Research
tags:
  - nutrient
  - primate
summary: "Let's think about nutrients"
---

Protein is important for primates, because it is the vital source for amino acids.


```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

When we talk about strategy, it is usually an action under a trade-off situation. So, we think the primate may intake AP and TNC with balance proportion.

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
month <- c(1:24)
AP <- seq(2,48,by=2)
TNC <- seq(1,24,by=1)

AP_v <- c(seq(0,5,by=1),seq(5,0,by=-1),seq(0,5,by=1),seq(5,0,by=-1))
TNC_v <- c(seq(5,0,by=-1),seq(0,5,by=1),seq(5,0,by=-1),seq(0,5,by=1))


AP_r <- sample(c(0:6),24,replace=TRUE)
TNC_r <- sample(c(0:6),24,replace=TRUE)

library(ggplot2)
d <- data.frame(month,AP,TNC)
i_stable <- ggplot(data=d,aes(month)) + ylim(0,6) +
  geom_hline(aes(yintercept = 2, colour="AP")) + 
  geom_hline(aes(yintercept = 1, colour="TNC")) +
  xlab("Month") + ylab("Nutrients intake") +
  theme_minimal()
p1 <- ggplot(data=d,aes(x=AP,y=TNC)) +
  geom_point() + 
  theme_minimal()
p2 <- ggplot(data=d,aes(x=cumsum(AP_v),y=cumsum(TNC_v))) + geom_point() +
  xlab("AP") + 
  ylab("TNC") +
  theme_minimal()
p3 <- ggplot(data=d,aes(x=cumsum(AP_r),y=cumsum(TNC_r))) + geom_point() +
  xlab("AP") + 
  ylab("TNC") +
  theme_minimal()



d_season <- data.frame(month,AP_v,TNC_v)
i_season <- ggplot(data=d_season,aes(month)) +
  ylim(0,6) +
  geom_line(aes(y = AP_v, colour="AP")) + 
  geom_line(aes(y = TNC_v, colour="TNC")) +
  xlab("Month") + ylab("Nutrients intake") +
  theme_minimal()

d_random <- data.frame(month,AP_r,TNC_r)
i_random <- ggplot(data=d_random,aes(month)) +
  ylim(0,6) +
  geom_line(aes(y = AP_r, colour="AP")) + 
  geom_line(aes(y = TNC_r, colour="TNC")) +
  xlab("Month") + ylab("Nutrients intake") +
  theme_minimal()

multiplot(i_stable, i_season, i_random, p1, p2, p3, cols=2)

```

And this strategy may be used to balance more nutrients.

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
n = 100
a <- numeric(n)
b <- numeric(n)
c <- numeric(n)
for(i in 1:n){
  a[i] <- sample(c(1:100),1)
  b[i] <- sample(c(1:(100-a[i])),1)
  if (a[i] + b[i] < 100) 
  {c[i] <- 100-(a[i]+b[i])}
  else {c[i] = 0}
}
f <- data.frame(a,b,c)
ggplot(data=f, aes(x=a,y=b)) + 
  geom_point() +
  xlab("AP") + 
  ylab("TNC") +
  theme_minimal()
  

```




