---
title: Step to Student Opening Report
author: Geebbon
date: '2018-03-13'
slug: step-to-student-opening-report
categories:
  - Student
tags:
  - Step work
summary: "Procedure to student opening report defence"
---

Anyway, I do some student work, including secretary working for opening report defencing. So I use grViz to make a step graph for the procedure. 


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
library(DiagrammeR)
grViz("
digraph boxes_and_circles {

  # a 'graph' statement
  graph [overlap = true, fontsize = 10]

  # several 'node' statements
  node [shape = box,
        fontname = Helvetica, color=OrangeRed]
  a [label = 'Defence Secretary'];
  b [label = 'Defence Chairman'];
  c [label = 'Teaching Secretary']; 
  d [label = 'All the students']; 
  e [label = 'All the teachers'] 

  # several 'edge' statements
  a -> b [label = 'determine the name list of student', arrowhead = diamond]
  a -> c [label = 'determine the date and classroom', arrowhead = diamond]
  c -> e [arrowhead = diamond]
  d -> e [arrowhead = diamond]
  a -> d [label = 'collect all the opening reports', arrowhead = diamond]
  a -> e [label = 'opening report defence with students', arrowhead = diamond]
}
")

```

Looks awful! 


After the defencing, I find almost all the students do not understand what they are going to do. Basically, all the students just follow the teachers' command, and not think by themselves, therefore, they fail to grab the core of research.

A opening defence for one student is limited in 5 minutes, so essentially if one student fail to grab the core, he does success in no way. It is not the matter whether the question is difficult, it is effort payed by the student.

In a simple way, for 5 minutes defence, one student have to answer several questions to himself.

* What do I want to tell my teacher? What is my research point? 
It is easy to suicide by telling the studying history. For example, I study time budget of primate in the opening period, my research point is the time budget. So I want to tell the teachers I want to study primate time budget for three reasons, the first is to understand how the primates adapt to the specific habitats; The second is to understand how the different individuals adjust their time budget to group living, or the difference among individuals varies in ages, breeding status, sex and social positions.

* Second step is to explain how I study. I use instantaneous scanning sample method with 5-minute interval, and I collect the behavioral data for 5 months, etc. 

* Finally, it is the conclusion. For university student, any conclusion from the experiment is acceptable. Such as I find difference among individuals at different ages, which implies the development affect the time budget. Or sex, or breeding status, etc.

The three steps way is not a trick, but a refining from the work. 5 minutes is enough for a university students work.

----
After the defence meeting, several problems were exposed. Of course it is good for correction in the future.

- 1 The first thing is almost all the students could not understand the aims of their research. 

- 2 All the students only know a little about their research, they can not answer the quesitons from review teachers, some questions are little further from the research.

- 3 All the students did not prepare or train for the defence meeting.





