---
title: What I want to tell about my research
author: Geebbon
date: '2018-03-19'
slug: what-i-want-to-tell-about-my-research
categories:
  - Student
tags:
  - Step work
summary:
  - "It should be information in the simplest way"
---

About primates, what do I want to tell the others?

It is about biodiversity, evolution, and human beings. 

To me, the gibbon is only one of the five hundreds of primate species, and the primates are only five hundreds of the ten millions of animal species. 

In Yunnan, most primates dwelled on forests. So all the stories can not happen without refering to forests. In case of we seeing a monkey or gibbon move in tree canopy, we want to know where they are going and what they are going to do. 

But the answers to these questions are difficult to get, we have to use some techniques and pay much efforts. From the simplest to the most difficult. 

At the begining, I was thinking if I can catch one, and ask him the questions. Of course it is not true, even I catch one, the monkey does not speak. 

What I have to do is doing research in scientific way, and resolve the questions. 

"Where are you going?" To answer this question, I have to follow the gibbon group for all days. Then I find out, they are heading to valley to forage ripe fruits; they are going to mountain ridge to bathe in the sun；they are going to patrol the habitat.

"What are you doing?" To answer the question, I have to observe them. Then I find out, they are foraging specific nutrient, such as protein; they sing every day for inter-group communication; they choose a proper and flat canopy for playing, which are important activity during their development stage. 

For year and year, the answers reveal their adaptation to forest living.

Why they exist, like all the lives, for inheritance of gene, mutation and their culture.