---
title: test a new post
author: guan
date: '2018-02-20'
slug: test-a-new-post
categories: []
tags: []
---
假设一个二项分布事件，要求估计出参数theta
```{r}
drive = c('texting','texting','texting','not','not',
          'texting','texting','not','not','texting')

# convert to numeric, arbitrarily picking texting=1, not=0
driveNum = ifelse(drive=='texting', 1, 0)
N = length(drive)                      # sample size
nTexting = sum(drive=='texting')       # number of drivers texting
nNot = sum(drive=='not')               # number of those not
```
我们武断设置一系列theta作为我们的先验概率，使用Kruschke方法限定先验概率接近0.5
```{r}
theta = seq(from=1/(N+1), to=N/(N+1), length=10)
### prior distribution
# uniform
# pTheta = dunif(theta)

# triangular as in Kruschke
pTheta = pmin(theta, 1-theta)

# beta prior with mean = .5
# pTheta = dbeta(theta, 10, 10)

pTheta = pTheta/sum(pTheta) # Normalize so sum to 1
```
根据二项分布的概率公式
p(y|theta)= (N choose k) \* theta^k \* (1-theta)^(N-k)，计算出p(y|theta)
```{r}
pDataGivenTheta = choose(N, nTexting) * theta^nTexting * (1-theta)^nNot
```
根据贝叶斯理论计算出后验概率
```{r}
# first we calculate the denominator from Bayes theorem; this is the marginal
# probability of y
pData = sum(pDataGivenTheta*pTheta)

pThetaGivenData = pDataGivenTheta*pTheta  / pData  # Bayes theorem
data.frame(theta, prior=pTheta, likelihood=pDataGivenTheta, posterior=pThetaGivenData)

```
结果来看，最大可能性likelihood建议的theta值 0.546-0.636。
```{r}
posteriorMean = sum(pThetaGivenData*theta)
posteriorMean
```
计算出后验概率均值0.5623611

